const MAP_SERVICE = {
	GOOGLE_MAPS: 'GOOGLE_MAPS',
	MAPY_COM: 'MAPY_COM',
	OPEN_STREET_MAP: 'OPEN_STREET_MAP',
};

const OLD_MAP_SERVICE = {
	MAPY_CZ: 'MAPY_CZ',
}

const MAP_SERVICE_HOSTNAME_FEATURE = {
	[MAP_SERVICE.GOOGLE_MAPS]: 'google.',
	[MAP_SERVICE.MAPY_COM]: 'mapy.com',
	[MAP_SERVICE.OPEN_STREET_MAP]: 'openstreetmap.org',
};